
{
    "Version": "2.0",
    "Statement": [
        {
            "runtime-version": "2.0",
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::march-pipe/*"
            ]
        }
    ]
}
