version: 0.2
env:
  variables:
    S3_BUCKET: "pipeline-march"
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on 'date'
      - ng build --configuration production --aot
  post_build:
     commands:
      - aws s3 cp dist s3://${pipeline-march} --recursive
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
