
    version: 0.2
phases:
   install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on 'date'
      - tsc
      - ng build 
    post_build:
      commands:
        - echo Build completed on `date`  

artifacts:
  files: "**/*"
  discard-paths: yes
  base-directory: 'dist/pipeline-march'
 
