version: 0.2
env:
  variables:
    S3_BUCKET: "pipeline-march"
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
     - ng build
     - ng build --watch --configuration development
  build:
    commands:
     - ng build --watch --configuration development
     - ng test
     - npm install && ng build
  post_build:
     commands:
      - aws s3 cp s3://pipeline-march
artifacts:
  files:
      - '**/*'
  base-directory: 'package.json'
  discard-paths: yes
