version: 0.2

env:
    variables:
        S3_BUCKET: "pipeline-march"
install:
    runtime-versions:
        nodejs: 10
    commands:
    - npm install -y npm@latest
    - npm install -g @angular/cli
    - rm package-lock.json
pre_build:
    commands:
    - npm install
build:
    commands:
    - echo build started on `date`
    - ng build
    - ls -l -F
post_build:
    commands:
            # Clear S3 bucket.
            - aws s3 rm s3://${pipeline-march} --recursive
            - echo S3 bucket is cleared.
            - aws s3 cp dist/{pipeline-march} s3://${pipeline-march} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '/'
    discard-paths: yes
    base-directory: 'dist/pipeline-march'
paths:
    - node_modules/

