version: 0.2
env:
  variables:
    S3_BUCKET: "pipeline-march"
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
    - ng build
  build:
    commands:
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
     - npm install && ng build
  post_build:
     commands:
      - aws s3 cp s3://pipeline-march
artifacts:
  files:
      - '**/*'
  base-directory: 'package.json'
  discard-paths: yes
