version: 0.2
env:
  variables:
    S3_BUCKET: "pipeline-march"
phases:
  install:
    runtime-versions:
      nodejs: 16.3.0
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
      - npm install -g @angular/cli@latest
  build:
    commands:
      - git init
      - git clone https://github.com/DiabolikElements/pipeline-march
      - ng build 
  post_build:
     commands:
      - aws s3 cp . s3://pipeline-march
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: no
