version: 0.2
env:
  variables:
    S3_BUCKET: "pipeline-march"
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
      - npm install -g @angular/cli@latest
      - npm install -g node@14.20.0
  build:
    commands:
     - npm install && npm run build
  post_build:
     commands:
      - aws s3 cp . s3://pipeline-march
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: no
